project:
  type: website
  post-render: 
    - "cp -rnv static/. _site" # source: https://github.com/quarto-dev/quarto-cli/discussions/4162#discussioncomment-4831352
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!2021-03-23-amia-informatics-summit/"
    - "!2022-02-11-tdw-ehr-lessons/"
    - "!2020-12-17-introduccion-xaringan/"
    - "!2020-08-31-tour-of-the-tidyverse/"

website:
  title: Silvia Canelón
  site-url: https://slides.silviacanelon.com/
  description: 'Collection of publicly available slide decks created by Silvia Canelón.'

  search: true
  favicon: assets/silvia/img/logo_rounded.svg
  navbar:
    # title: false
    logo: assets/silvia/img/logo_noBg.svg
    logo-alt: "Home" #doesn't seem to show up
    tools:
      - icon: github
        href: https://www.github.com/spcanelon/slides

  #opengraph: true
  twitter-card:
    creator: "@spcanelon"
    image: "/img/social-card.png"

  page-footer:  
    left: >-
     &#169; 2023 [Silvia Canelón](https://silviacanelon.com) &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="https://silviacanelon.com/accessibility" title="Accessibility commitment" target="_blank" rel="noopener">{{< fa universal-access >}}</a>
      <a class="link-dark me-1" href="https://hachyderm.io/@spcanelon" title="mastodon" target="_blank" rel="noopener">{{< fa brands mastodon >}}</a>
      <a class="link-dark me-1" href="https://github.com/spcanelon" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0003-1709-1394" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=GAzkvpcAAAAJ&hl=en&oi=ao" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
      <a class="link-dark me-1" href="https://linkedin.com/in/spcanelon" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>

    right: 
      - text: "Accessibility"
        aria-label: "Accessibility Commitment"
        href: https://silviacanelon.com/accessibility
      - text: "Contact"
        aria-label: "Contact Form"
        href: https://silviacanelon.com/contact
      - text: "License"
        aria-label: "License Details"
        href: https://silviacanelon.com/license
      - icon: rss
        href: index.xml

format: 
  html:
    theme:
      light:
        - cosmo
        # - superhero
        - assets/silvia-theme.scss
        - assets/silvia/colors.scss
        - assets/silvia/fonts.scss
    highlight-style: a11y
    code-link: true

execute:
  freeze: auto

include-in-header: assets/umami.html
